# Generated by Django 4.2.1 on 2023-06-04 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newclient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.friend')),
            ],
        ),
        migrations.AddField(
            model_name='borrowed',
            name='client',
            field=models.ManyToManyField(to='rental.newclient'),
        ),
    ]
